### ISSUE TITLE
安装到手机上时build fail

### ISSUE THREAD

**Issue by JeremyDa** [songkuixi/ARBottleJump#1]
主要错误信息如下：
/Users/xx/Library/Developer/Xcode/DerivedData/ARBottleJump-dklrrigunhsfieepebllmehjxwah/Build/Products/Debug-iphoneos/ARBottleJump.app/Frameworks/libswiftARKit.dylib: unknown error -1=ffffffffffffffff
error: Task failed with exit 1 signal 0 {
	/usr/bin/codesign '--force' '--sign' 'xxxxxxxxx' '--verbose' '/Users/xx/Library/Developer/Xcode/DerivedData/ARBottleJump-dklrrigunhsfieepebllmehjxwah/Build/Products/Debug-iphoneos/ARBottleJump.app/Frameworks/libswiftARKit.dylib'
}
请问是什么原因

**Comment by krayc425** [comment]
@JeremyDa 清空一下 DerivedData 文件夹试试看？

**Comment by JeremyDa** [comment]
清空DerivedData文件夹后仍提示这个错。
根据https://www.jianshu.com/p/f31116a76ea9提示，
将签名信息改为了个人AppleId，Bundle Identifier 修改了换了个名字。

**Comment by JeremyDa** [comment]
xcode版本是9.2

**Comment by JeremyDa** [comment]
重启电脑，重启xcode，build时提示Keychian Access，选择“始终允许” 就ok了
