### ISSUE TITLE
作者好，我下载后运行并没有出现gif上的效果，只有一个xyz轴线

### ISSUE THREAD

**Issue by karson711** [songkuixi/ARBottleJump#2]

**Comment by krayc425** [comment]
@karson711 ARKit 要求开启应用以后四处移动一下，采集到一定数量的特征点才能开始工作，请在屏幕上出现“Touch anywhere to begin”以后再点击屏幕开始。

**Comment by muzesunshine** [comment]
Me Too

**Comment by krayc425** [comment]
@muzesunshine @karson711 请拿着手机四处走动，等屏幕上出现“Touch anywhere to begin”以后再点击屏幕开始。

**Comment by wangxiaodan820** [comment]
6666
