### ISSUE TITLE
确定可以用？还是出来忽悠人的？

### ISSUE THREAD

**Issue by Liangxue** [songkuixi/ARBottleJump#3]
确定可以用？还是出来忽悠人的？

**Comment by krayc425** [comment]
@Liangxue 不知道您遇到了什么问题 但是我有必要出来忽悠人吗？ ARKit 要求开启应用以后四处移动一下，采集到一定数量的特征点才能开始工作，请在屏幕上出现“Touch anywhere to begin”以后再点击屏幕开始。

**Comment by Liangxue** [comment]
是的呢，同意之后只会出现一个三维坐标柱子，您可以下载下来试试

**Comment by krayc425** [comment]
@Liangxue 你没听懂吗……要拿着手机四处走动走动 然后等屏幕出现提示

**Comment by Liangxue** [comment]
哦哦，明白了，不好意思
